### ISSUE TITLE
Добавление работы c ble

### ISSUE THREAD

**Issue by kraa965** [MichaelDworkin/Arduino-USB-Macro-Keyboard-Russian#1]
Добрый день
Увидел вашу работу, очень заинтересовал вопрос, можно ли вашу работу объединить с https://github.com/T-vK/ESP32-BLE-Keyboard чтобы можно было по нажатию кнопки выводить русский текст по блютузу?

**Comment by MichaelDworkin** [comment]
Здравствуйте,я не вижу принципиальных ограничений. Однако я давно уже не занимаюсь этой темой и не смогу помочь.
    Am Mittwoch, 17. Mai 2023 um 18:00:59 MESZ hat Wolf_965 ***@***.***> Folgendes geschrieben:  
 
 


Добрый день
Увидел вашу работу, очень заинтересовал вопрос, можно ли вашу работу объединить с https://github.com/T-vK/ESP32-BLE-Keyboard чтобы можно было по нажатию кнопки выводить русский текст по блютузу?

**Comment by kraa965** [comment]
Жаль, вчера объединил две библиотеки в одну, русский текст выводится корректно, но системные клавиши Enter и др. выводятся буквами, думал, может как-то можно изменить функцию, чтобы буквы выводились русские, а системные кнопки определялись таким образом 
`const uint8_t KEY_UP_ARROW = 0xDA;
const uint8_t KEY_DOWN_ARROW = 0xD9;
const uint8_t KEY_LEFT_ARROW = 0xD8;
const uint8_t KEY_RIGHT_ARROW = 0xD7;`
